#!/bin/bash
case $1 in
start)
    echo “Removendo as permissoes de execucao das particoes”
    mount -o remount,rw,noexec /home
    mount -o remount,rw,noexec /tmp
    mount
    echo “Particoes SEM permissoes de execucao”
    exit 0
;;
stop)
    echo “Habilitando permissoes de execucao das particoes
    mount -o remount,rw,exec /home
    mount -o remount,rw,exec /tmp
    mount
    echo “Particoes COM permissao de execucao
    exit 0
;;

*) echo Use $0 “{start/stop}”
exit 0
;;
esac
exit 1
